// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: pkg/proto/dbc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecodedSignal struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MessageName string                 `protobuf:"bytes,1,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Raw:
	//
	//	*DecodedSignal_RawU
	//	*DecodedSignal_RawS
	//	*DecodedSignal_RawF
	//	*DecodedSignal_RawB
	//	*DecodedSignal_RawBytes
	Raw           isDecodedSignal_Raw    `protobuf_oneof:"raw"`
	Physical      *float64               `protobuf:"fixed64,8,opt,name=physical,proto3,oneof" json:"physical,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Signal        *Signal                `protobuf:"bytes,10,opt,name=signal,proto3" json:"signal,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CanId         uint32                 `protobuf:"varint,12,opt,name=can_id,json=canId,proto3" json:"can_id,omitempty"`
	IsExtended    bool                   `protobuf:"varint,13,opt,name=is_extended,json=isExtended,proto3" json:"is_extended,omitempty"`
	FrameBytes    []byte                 `protobuf:"bytes,14,opt,name=frame_bytes,json=frameBytes,proto3" json:"frame_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedSignal) Reset() {
	*x = DecodedSignal{}
	mi := &file_pkg_proto_dbc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedSignal) ProtoMessage() {}

func (x *DecodedSignal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dbc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedSignal.ProtoReflect.Descriptor instead.
func (*DecodedSignal) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dbc_proto_rawDescGZIP(), []int{0}
}

func (x *DecodedSignal) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

func (x *DecodedSignal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DecodedSignal) GetRaw() isDecodedSignal_Raw {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *DecodedSignal) GetRawU() uint64 {
	if x != nil {
		if x, ok := x.Raw.(*DecodedSignal_RawU); ok {
			return x.RawU
		}
	}
	return 0
}

func (x *DecodedSignal) GetRawS() int64 {
	if x != nil {
		if x, ok := x.Raw.(*DecodedSignal_RawS); ok {
			return x.RawS
		}
	}
	return 0
}

func (x *DecodedSignal) GetRawF() float64 {
	if x != nil {
		if x, ok := x.Raw.(*DecodedSignal_RawF); ok {
			return x.RawF
		}
	}
	return 0
}

func (x *DecodedSignal) GetRawB() bool {
	if x != nil {
		if x, ok := x.Raw.(*DecodedSignal_RawB); ok {
			return x.RawB
		}
	}
	return false
}

func (x *DecodedSignal) GetRawBytes() []byte {
	if x != nil {
		if x, ok := x.Raw.(*DecodedSignal_RawBytes); ok {
			return x.RawBytes
		}
	}
	return nil
}

func (x *DecodedSignal) GetPhysical() float64 {
	if x != nil && x.Physical != nil {
		return *x.Physical
	}
	return 0
}

func (x *DecodedSignal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DecodedSignal) GetSignal() *Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *DecodedSignal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DecodedSignal) GetCanId() uint32 {
	if x != nil {
		return x.CanId
	}
	return 0
}

func (x *DecodedSignal) GetIsExtended() bool {
	if x != nil {
		return x.IsExtended
	}
	return false
}

func (x *DecodedSignal) GetFrameBytes() []byte {
	if x != nil {
		return x.FrameBytes
	}
	return nil
}

type isDecodedSignal_Raw interface {
	isDecodedSignal_Raw()
}

type DecodedSignal_RawU struct {
	RawU uint64 `protobuf:"varint,3,opt,name=raw_u,json=rawU,proto3,oneof"`
}

type DecodedSignal_RawS struct {
	RawS int64 `protobuf:"zigzag64,4,opt,name=raw_s,json=rawS,proto3,oneof"`
}

type DecodedSignal_RawF struct {
	RawF float64 `protobuf:"fixed64,5,opt,name=raw_f,json=rawF,proto3,oneof"`
}

type DecodedSignal_RawB struct {
	RawB bool `protobuf:"varint,6,opt,name=raw_b,json=rawB,proto3,oneof"`
}

type DecodedSignal_RawBytes struct {
	RawBytes []byte `protobuf:"bytes,7,opt,name=raw_bytes,json=rawBytes,proto3,oneof"`
}

func (*DecodedSignal_RawU) isDecodedSignal_Raw() {}

func (*DecodedSignal_RawS) isDecodedSignal_Raw() {}

func (*DecodedSignal_RawF) isDecodedSignal_Raw() {}

func (*DecodedSignal_RawB) isDecodedSignal_Raw() {}

func (*DecodedSignal_RawBytes) isDecodedSignal_Raw() {}

type Signal struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Start             uint32                 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Length            uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	IsBigEndian       bool                   `protobuf:"varint,4,opt,name=is_big_endian,json=isBigEndian,proto3" json:"is_big_endian,omitempty"`
	IsSigned          bool                   `protobuf:"varint,5,opt,name=is_signed,json=isSigned,proto3" json:"is_signed,omitempty"`
	IsFloat           bool                   `protobuf:"varint,6,opt,name=is_float,json=isFloat,proto3" json:"is_float,omitempty"`
	IsMultiplexer     bool                   `protobuf:"varint,7,opt,name=is_multiplexer,json=isMultiplexer,proto3" json:"is_multiplexer,omitempty"`
	IsMultiplexed     bool                   `protobuf:"varint,8,opt,name=is_multiplexed,json=isMultiplexed,proto3" json:"is_multiplexed,omitempty"`
	MultiplexerValue  uint32                 `protobuf:"varint,9,opt,name=multiplexer_value,json=multiplexerValue,proto3" json:"multiplexer_value,omitempty"`
	Offset            float64                `protobuf:"fixed64,10,opt,name=offset,proto3" json:"offset,omitempty"`
	Scale             float64                `protobuf:"fixed64,11,opt,name=scale,proto3" json:"scale,omitempty"`
	Min               float64                `protobuf:"fixed64,12,opt,name=min,proto3" json:"min,omitempty"`
	Max               float64                `protobuf:"fixed64,13,opt,name=max,proto3" json:"max,omitempty"`
	Unit              string                 `protobuf:"bytes,14,opt,name=unit,proto3" json:"unit,omitempty"`
	Description       string                 `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	ValueDescriptions []*ValueDescription    `protobuf:"bytes,16,rep,name=value_descriptions,json=valueDescriptions,proto3" json:"value_descriptions,omitempty"`
	ReceiverNodes     []string               `protobuf:"bytes,17,rep,name=receiver_nodes,json=receiverNodes,proto3" json:"receiver_nodes,omitempty"`
	DefaultValue      int32                  `protobuf:"varint,18,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	SourceFile        string                 `protobuf:"bytes,19,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_pkg_proto_dbc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dbc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dbc_proto_rawDescGZIP(), []int{1}
}

func (x *Signal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Signal) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Signal) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Signal) GetIsBigEndian() bool {
	if x != nil {
		return x.IsBigEndian
	}
	return false
}

func (x *Signal) GetIsSigned() bool {
	if x != nil {
		return x.IsSigned
	}
	return false
}

func (x *Signal) GetIsFloat() bool {
	if x != nil {
		return x.IsFloat
	}
	return false
}

func (x *Signal) GetIsMultiplexer() bool {
	if x != nil {
		return x.IsMultiplexer
	}
	return false
}

func (x *Signal) GetIsMultiplexed() bool {
	if x != nil {
		return x.IsMultiplexed
	}
	return false
}

func (x *Signal) GetMultiplexerValue() uint32 {
	if x != nil {
		return x.MultiplexerValue
	}
	return 0
}

func (x *Signal) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Signal) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Signal) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Signal) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Signal) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Signal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Signal) GetValueDescriptions() []*ValueDescription {
	if x != nil {
		return x.ValueDescriptions
	}
	return nil
}

func (x *Signal) GetReceiverNodes() []string {
	if x != nil {
		return x.ReceiverNodes
	}
	return nil
}

func (x *Signal) GetDefaultValue() int32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Signal) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

type ValueDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueDescription) Reset() {
	*x = ValueDescription{}
	mi := &file_pkg_proto_dbc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueDescription) ProtoMessage() {}

func (x *ValueDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dbc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueDescription.ProtoReflect.Descriptor instead.
func (*ValueDescription) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dbc_proto_rawDescGZIP(), []int{2}
}

func (x *ValueDescription) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ValueDescription) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_pkg_proto_dbc_proto protoreflect.FileDescriptor

const file_pkg_proto_dbc_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/dbc.proto\x12\x12candecode.proto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x03\n" +
	"\rDecodedSignal\x12!\n" +
	"\fmessage_name\x18\x01 \x01(\tR\vmessageName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x05raw_u\x18\x03 \x01(\x04H\x00R\x04rawU\x12\x15\n" +
	"\x05raw_s\x18\x04 \x01(\x12H\x00R\x04rawS\x12\x15\n" +
	"\x05raw_f\x18\x05 \x01(\x01H\x00R\x04rawF\x12\x15\n" +
	"\x05raw_b\x18\x06 \x01(\bH\x00R\x04rawB\x12\x1d\n" +
	"\traw_bytes\x18\a \x01(\fH\x00R\brawBytes\x12\x1f\n" +
	"\bphysical\x18\b \x01(\x01H\x01R\bphysical\x88\x01\x01\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x122\n" +
	"\x06signal\x18\n" +
	" \x01(\v2\x1a.candecode.proto.v1.SignalR\x06signal\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x15\n" +
	"\x06can_id\x18\f \x01(\rR\x05canId\x12\x1f\n" +
	"\vis_extended\x18\r \x01(\bR\n" +
	"isExtended\x12\x1f\n" +
	"\vframe_bytes\x18\x0e \x01(\fR\n" +
	"frameBytesB\x05\n" +
	"\x03rawB\v\n" +
	"\t_physical\"\xeb\x04\n" +
	"\x06Signal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05start\x18\x02 \x01(\rR\x05start\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\x12\"\n" +
	"\ris_big_endian\x18\x04 \x01(\bR\visBigEndian\x12\x1b\n" +
	"\tis_signed\x18\x05 \x01(\bR\bisSigned\x12\x19\n" +
	"\bis_float\x18\x06 \x01(\bR\aisFloat\x12%\n" +
	"\x0eis_multiplexer\x18\a \x01(\bR\risMultiplexer\x12%\n" +
	"\x0eis_multiplexed\x18\b \x01(\bR\risMultiplexed\x12+\n" +
	"\x11multiplexer_value\x18\t \x01(\rR\x10multiplexerValue\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\x01R\x06offset\x12\x14\n" +
	"\x05scale\x18\v \x01(\x01R\x05scale\x12\x10\n" +
	"\x03min\x18\f \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\r \x01(\x01R\x03max\x12\x12\n" +
	"\x04unit\x18\x0e \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescription\x12S\n" +
	"\x12value_descriptions\x18\x10 \x03(\v2$.candecode.proto.v1.ValueDescriptionR\x11valueDescriptions\x12%\n" +
	"\x0ereceiver_nodes\x18\x11 \x03(\tR\rreceiverNodes\x12#\n" +
	"\rdefault_value\x18\x12 \x01(\x05R\fdefaultValue\x12\x1f\n" +
	"\vsource_file\x18\x13 \x01(\tR\n" +
	"sourceFile\"J\n" +
	"\x10ValueDescription\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescriptionB.Z,github.com/BIwashi/candecode/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_dbc_proto_rawDescOnce sync.Once
	file_pkg_proto_dbc_proto_rawDescData []byte
)

func file_pkg_proto_dbc_proto_rawDescGZIP() []byte {
	file_pkg_proto_dbc_proto_rawDescOnce.Do(func() {
		file_pkg_proto_dbc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_dbc_proto_rawDesc), len(file_pkg_proto_dbc_proto_rawDesc)))
	})
	return file_pkg_proto_dbc_proto_rawDescData
}

var file_pkg_proto_dbc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_dbc_proto_goTypes = []any{
	(*DecodedSignal)(nil),         // 0: candecode.proto.v1.DecodedSignal
	(*Signal)(nil),                // 1: candecode.proto.v1.Signal
	(*ValueDescription)(nil),      // 2: candecode.proto.v1.ValueDescription
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_pkg_proto_dbc_proto_depIdxs = []int32{
	1, // 0: candecode.proto.v1.DecodedSignal.signal:type_name -> candecode.proto.v1.Signal
	3, // 1: candecode.proto.v1.DecodedSignal.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: candecode.proto.v1.Signal.value_descriptions:type_name -> candecode.proto.v1.ValueDescription
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_dbc_proto_init() }
func file_pkg_proto_dbc_proto_init() {
	if File_pkg_proto_dbc_proto != nil {
		return
	}
	file_pkg_proto_dbc_proto_msgTypes[0].OneofWrappers = []any{
		(*DecodedSignal_RawU)(nil),
		(*DecodedSignal_RawS)(nil),
		(*DecodedSignal_RawF)(nil),
		(*DecodedSignal_RawB)(nil),
		(*DecodedSignal_RawBytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_dbc_proto_rawDesc), len(file_pkg_proto_dbc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_dbc_proto_goTypes,
		DependencyIndexes: file_pkg_proto_dbc_proto_depIdxs,
		MessageInfos:      file_pkg_proto_dbc_proto_msgTypes,
	}.Build()
	File_pkg_proto_dbc_proto = out.File
	file_pkg_proto_dbc_proto_goTypes = nil
	file_pkg_proto_dbc_proto_depIdxs = nil
}
